const audio_resources = [
  {element : 'audio', label : 'ずんだもんだよ', states : { 'src' : "./voice/001_ずんだもん（セクシー）_ずんだもんだよ.wav"}},
  {element : 'audio', label : 'エックス', states : { 'src' : "./voice/002_ずんだもん（ツンツン）_エックス.wav"}},
  {element : 'audio', label : 'エエエエックス', states : { 'src' : "./voice/003_ずんだもん（ツンツン）_エエエエックス.wav"}},
  {element : 'audio', label : 'マンボウ', states : { 'src' : "./voice/004_ずんだもん（セクシー）_マンボウ.wav"}},
  {element : 'audio', label : 'スペシャルスクラッチ', states : { 'src' : "./voice/005_ずんだもん（ノーマル）_スペシャルスクラッチ.wav"}},
  {element : 'audio', label : 'ウェルカム', states : { 'src' : "./voice/006_ずんだもん（ノーマル）_ウェルカム、トゥー….wav"}},
  {element : 'audio', label : 'ありがとうございます', states : { 'src' : "./voice/007_ずんだもん（あまあま）_ありがとうございます.wav"}},
  {element : 'audio', label : 'バイバイ', states : { 'src' : "./voice/008_ずんだもん（セクシー）_バイバーイ.wav"}},
  {element : 'audio', label : 'ウェブマネー', states : { 'src' : "./voice/009_ずんだもん（ささやき）_ウェブマネー.wav"}},
  {element : 'audio', label : 'ビットキャッシュ', states : { 'src' : "./voice/010_ずんだもん（ヒソヒソ）_ビットキャッシュ.wav"}},
  {element : 'audio', label : 'ポイント', states : { 'src' : "./voice/011_ずんだもん（ノーマル）_ポイント.wav"}},
  {element : 'audio', label : 'キノコ', states : { 'src' : "./voice/012_ずんだもん（ノーマル）_キノコ.wav"}},
  {element : 'audio', label : 'インフルエンサー', states : { 'src' : "./voice/013_ずんだもん（ノーマル）_インフルエンサー.wav"}},
  {element : 'audio', label : 'ゴメンゴメン', states : { 'src' : "./voice/014_ずんだもん（ツンツン）_ゴメンゴメン.wav"}},
  {element : 'audio', label : 'プリプリ', states : { 'src' : "./voice/015_ずんだもん（セクシー）_プリプリ.wav"}},
  {element : 'audio', label : 'ぽっぽー', states : { 'src' : "./voice/016_ずんだもん（セクシー）_ぽっぽー.wav"}},
  {element : 'audio', label : 'おじさんスタイル', states : { 'src' : "./voice/017_ずんだもん（ヒソヒソ）_おじさんスタイル.wav"}},
  {element : 'audio', label : 'キーン', states : { 'src' : "./voice/018_ずんだもん（ヒソヒソ）_キーーーン.wav"}},
  {element : 'audio', label : 'パパパパパ', states : { 'src' : "./voice/019_ずんだもん（ヒソヒソ）_パパパパパ.wav"}},
  {element : 'audio', label : 'オブザワイルド', states : { 'src' : "./voice/020_ずんだもん（ノーマル）_オブザワイルド.wav"}},
  {element : 'audio', label : 'とってもチャーミング', states : { 'src' : "./voice/021_ずんだもん（あまあま）_とってもチャーミング.wav"}},
  {element : 'audio', label : 'どどん', states : { 'src' : "./voice/022_ずんだもん（あまあま）_どどん.wav"}},
  {element : 'audio', label : 'ラスボス', states : { 'src' : "./voice/023_ずんだもん（あまあま）_ラスボス.wav"}},
  //{element : 'audio', label : '', states : { 'src' : ""}},

]